<script type="text/javascript" src="/typo3conf/ext/wildsidemvc/js/dojo/dojo.js" djConfig="isDebug: false, parseOnLoad: true, usePlainJson:true"></script>
<link href="/typo3conf/ext/wildsidemvc/js/dojo/resources/dojo.css" rel="stylesheet" type="text/css" />
<link href="/typo3conf/ext/wildsidemvc/js/dijit/themes/tundra/tundra.css" rel="stylesheet" type="text/css" />
<style type="text/css" id="generatedStyles"></style>